### ISSUE TITLE
Unable to change image of container

### ISSUE THREAD

**Issue by reste85** [B23admin/nifi-stateless-operator#11]
Hi, 
First of all thank you for this operator. 
During our tests, we've found that we're unable to change the image of the underlying Job. If i specify the "image" configuration into the spec of the yaml, it gets ignored. 
We've installed the operator directly with this script (without building from code): 

`kubectl apply -f https://raw.githubusercontent.com/b23llc/nifi-stateless-operator/master/config/deploy/nifi-stateless-operator.yaml
`

has anyone experienced this problem?

here our CR that we're using to deploy the job:

```
apiVersion: nififn.nifi-stateless.b23.io/v1alpha1
kind: NiFiFn
metadata:
  name: nififn-sample-s3-delivery
  namespace: nifi-stateless-operator-system
spec:
  image: "apache/nifi-stateless:1.10.0"
  runFrom: registry
  registryUrl: "http://nifi-registry-location:80"
  bucketId: "6e923cce-0e83-4f48-a8d7-0f3790ea1021"
  flowId: "897ddd1b-e89b-49b5-8731-da751dbfefec"
  flowVersion: 5
  flowFiles:
  - s3.bucket: our-bucket
    filename: source/test.parquet
    filename_dest: test/test.parquet
    s3.destination.bucket: test-bucket
 
```

i want to change the base image because we're hitting the following problem: 
"Caused by: java.lang.IllegalArgumentException: FetchS3Object[id=9cd5b00d-ab5f-3da2-97a9-a04d9757a016] is not valid: 'requester-pays' validated against 'false' is invalid because 'requester-pays' is not a supported property or has no Validator associated with it"

And the flow correctly works with NiFi 1.10.0-RC3
